### ISSUE TITLE
Feature not displayed and wrong coordinates with EPSG different from 4326

### ISSUE THREAD

**Issue by paolabfor** [IZSVenezie/VetEpiGIS-Tool#4]
Points and polygons not displayed and wrong coordinates in "Add case" and "Add POI" windows when QGIS3 CRS project is not in EPSG:4326.
![Wrong coordinate](https://user-images.githubusercontent.com/53217629/63685859-b690aa00-c800-11e9-89f6-2a94933d392e.jpg)
![Wrong_coordinate_POI](https://user-images.githubusercontent.com/53217629/63685862-b690aa00-c800-11e9-9f1a-2f349dc9b1de.jpg)

**Comment by mmazzucato** [comment]
Closed.
